"""Toffoli+Clifford+T+QRAM resource ledger for the 14 solver-stack input-model cases.

Reuses the closed RIR artifacts generated by examples/input_models.py
(out/input-models/) and performs compositional resource estimation per case:
gate-level cost and QRAM query counts are compared on the same problem across
different data paths (structured gate ports / spectral embedding / QRAM). If
the artifacts are missing, first run `PYTHONPATH=src python
examples/input_models.py`.

Run: PYTHONPATH=src python tools/build_qram_queries.py [--cases out/input-models]
"""

import argparse
import json
from pathlib import Path

from oracq import estimate_resources, loads

CASES = Path("out/input-models")
OUT = Path("out/resource-estimates")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", type=Path, default=CASES, help="directory of closed RIR cases")
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT / "solver_qram_queries.json",
        help="output path of the ledger artifact",
    )
    args = parser.parse_args()
    if not args.cases.is_dir():
        raise SystemExit(f"Missing artifacts under {args.cases}; please run examples/input_models.py first")
    records = []
    for folder in sorted(args.cases.iterdir()):
        closed = folder / "closed.rir.yaml"
        if not closed.is_file():
            continue
        program = loads(closed.read_text(encoding="utf-8"))
        report = json.loads((folder / "report.json").read_text(encoding="utf-8"))
        estimate = estimate_resources(program)
        record = {
            "case": folder.name,
            "family": folder.name.split("_", 1)[0],
            "resources": report["resources"],
            "modules": report["modules"],
            **estimate.to_dict(),
        }
        records.append(record)
        print(
            f"{folder.name:28s} qubits={estimate.qubits:4d} toffoli={estimate.toffoli:7d} "
            f"t_exact={estimate.t_exact:4d} rot={len(estimate.rotations):5d} "
            f"qram={estimate.qram_total:3d} {dict(estimate.qram_queries)}",
            flush=True,
        )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "group": "solver_qram_queries",
        "note": "resource ledger for the 14 closed cases in out/input-models; comparison across data paths on the same problem",
        "records": records,
    }
    args.out.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"[artifact] {args.out}", flush=True)


if __name__ == "__main__":
    main()
